# Debian configuration for use Caddy with Symfony
FROM dunglas/frankenphp:1-builder-php8.3 AS builder

# Copy xcaddy in the builder image
COPY --from=caddy:builder /usr/bin/xcaddy /usr/bin/xcaddy

# CGO must be enabled to build FrankenPHP
ENV CGO_ENABLED=1 XCADDY_SETCAP=1 XCADDY_GO_BUILD_FLAGS=$'-ldflags "-w -s -extldflags \'-Wl,-z,stack-size=0x80000\'"'
RUN xcaddy build \
	--output /usr/local/bin/frankenphp \
	--with github.com/dunglas/frankenphp=./ \
	--with github.com/dunglas/frankenphp/caddy=./caddy/ \
	--with github.com/dunglas/caddy-cbrotli \
	# Mercure and Vulcain are included in the official build, but feel free to remove them
	--with github.com/dunglas/mercure/caddy \
	--with github.com/dunglas/vulcain/caddy
	# Add extra Caddy modules here

FROM dunglas/frankenphp:1.4-builder-php8.3 AS upstream

FROM upstream AS base

ARG GROUP_NAME=www-data
ARG USER_NAME=www-data
ARG USER_ID=1000
ARG GROUP_ID
ARG APP_DIR=/app

WORKDIR /${APP_DIR}

COPY --link app/Caddyfile /etc/caddy/Caddyfile


RUN groupadd --g ${GROUP_ID} ${USER_NAME}; \
	useradd -u ${USER_ID} -g ${USER_NAME} -g ${GROUP_NAME} -m ${USER_NAME}; \
	setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/frankenphp; \
	chown -R ${USER_NAME}:${USER_NAME} /data/caddy && chown -R ${USER_NAME}:${USER_NAME} /config/caddy

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y locales apt-utils git libicu-dev g++ libpng-dev \
    libxml2-dev libzip-dev libonig-dev libxslt-dev gconf-service libasound2 \
    libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 \
    libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
    libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
    libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 \
    libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release \
    xdg-utils wget libgbm-dev libxshmfence-dev zip \ 
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

RUN     echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
        echo "fr_FR.UTF-8 UTF-8" >> /etc/locale.gen && \
        locale-gen

RUN docker-php-ext-configure intl
RUN docker-php-ext-install pdo pdo_mysql gd opcache intl zip calendar dom mbstring gd xsl pcntl sockets xml
RUN pecl install apcu && docker-php-ext-enable apcu

RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls && \
    mv composer.phar /usr/local/bin/composer

FROM base AS dev

# install symfony cli
RUN curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash && \
    apt install symfony-cli -y && rm -rf /var/cache/apt/archives /var/lib/apt/lists

# install xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug

# configure xdebug
RUN echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.log=/app/var/log/xdebug.log" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.discover_client_host=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.client_port=9000" >> /usr/local/etc/php/conf.d/xdebug.ini

USER ${USER_NAME}


# COPY --link app/worker.dev.Caddyfile /etc/caddy/worker.Caddyfile
# ENV FRANKENPHP_CONFIG="import worker.Caddyfile"

CMD [ "frankenphp", "run", "--config", "/etc/caddy/Caddyfile" ]

FROM base AS prod

ENV APP_ENV=prod

COPY --link app/worker.prod.Caddyfile /etc/caddy/worker.Caddyfile

ENV FRANKENPHP_CONFIG="import worker.Caddyfile"

USER ${USER_NAME}

CMD [ "frankenphp", "run", "--config", "/etc/caddy/Caddyfile" ]