services:
  app:
    labels:
      - "traefik.http.routers.${PROJECT_NAME}-app.rule=Host(`${PROJECT_NAME}-app.localhost`)"
    depends_on:
      - traefik
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
      restart: 'no'
    ports:
      - 8081:80
    labels:
      - "traefik.http.routers.${PROJECT_NAME}-myadmin.rule=Host(`${PROJECT_NAME}-myadmin.localhost`)"
    depends_on:
      - traefik
      - db
    networks:
      - network
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-mailer.rule=Host(`${PROJECT_NAME}-mailer.localhost`)"
      - "traefik.http.routers.${PROJECT_NAME}-mailer.entrypoints=http"
      - "traefik.http.services.${PROJECT_NAME}-mailer.loadbalancer.server.port=1080"
    depends_on:
      - traefik
      - db
    networks:
      - network
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    # command: --api.insecure=true --providers.docker
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      # - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      # - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network