services:
  app:
    labels:
      - "traefik.http.routers.${PROJECT_NAME}-app.rule=Host(`${PROJECT_NAME}-app.localhost`)"
    depends_on:
      - traefik
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
      restart: 'no'
    ports:
      - 8081:80
    labels:
      - "traefik.http.routers.${PROJECT_NAME}-myadmin.rule=Host(`${PROJECT_NAME}-myadmin.localhost`)"
    depends_on:
      - traefik
      - db
    networks:
      - network
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-mailer.rule=Host(`${PROJECT_NAME}-mailer.localhost`)"
      - "traefik.http.routers.${PROJECT_NAME}-mailer.entrypoints=http"
      - "traefik.http.services.${PROJECT_NAME}-mailer.loadbalancer.server.port=8025"
    depends_on:
      - traefik
    networks:
      - network
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - mailer-data:/data
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network
volumes:
  caddy_data:
  caddy_config:
  db_data: null
  mailer-data: null